# Generated by Django 4.2.4 on 2024-06-11 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.TextField(max_length=32)),
                ('username', models.TextField(max_length=32)),
                ('link', models.URLField()),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
