# Generated by Django 4.2.4 on 2024-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_album_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
